name: Playwright Tests
on:
  push:
    branches: [ githubCI ]
  pull_request:
    branches: [ githubCI ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install
    - name: Start 
      run: npm run dev
    - name: Run Playwright tests
      run: npx playwright test test.spec.js 
    